name: Decomission Preview Environment

on:
  pull_request:
    types:
      - closed

jobs:
  cleanup:
    name: Delete Stack
    runs-on: ubuntu-20.04

    if: ${{ startsWith(github.event.pull_request.head.ref, 'feat/') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Extract branch name
        uses: frabert/replace-string-action@v1.2
        id: extract_branch
        with:
          pattern: feat/(.*)
          string: ${{ github.event.pull_request.head.ref }}
          replace-with: $1

      - name: Delete Stack
        run: |
          aws cloudformation delete-stack --stack-name ${{ steps.extract_branch.outputs.replaced }}-Application
          aws cloudformation wait stack-delete-complete --stack-name ${{ steps.extract_branch.outputs.replaced }}-Application